scan_filter_chain:
- name: range
  type: LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.25
    upper_threshold: 10.0
    lower_replacement_value: 0
    upper_replacement_value: 0
